{% set name = "seams-core" %}
{% set version = "1.0.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/d-SEAMS/seams-core/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b71c7b0665b4c44c9ae6071a09f1ef86ed50b661bcfa12e2e002a86c28f8114f
build:
  number: 0
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - git
    - luarocks
    - lua {{ lua }}
    # - lua-luafilesystem
    - eigen
    - yaml-cpp
    - blas
    - lapack
    - boost {{ boost }}
    - gsl
    - fmt
    - rang
    - catch2
    - wget
    - unzip
    - make  # [unix]
    - pkg-config  # [not win]
  host:
    - boost-cpp
    - yaml-cpp
    - fmt
  run:
    - luarocks
    - lua {{ lua }}
test:
  # requires:
  #   - luarocks
  #   - lua-luafilesystem
  commands:
    - "yodaStruct -c lua_inputs/config.yml"
about:
  home: https://dseams.info
  license:  GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Deferred Structural Elucidation Analysis for Molecular Simulations'
  description: |
    d-SEAMS is a collection of analysis tools for molecular simulations. It has
    been implemented with an engine in C++, and extensions via the Lua scripting
    interface. The code sheds light on the structures from simulation
    trajectories, in terms of their topology and it has been tailored for the
    analysis of nucleating systems. The framework is meant to be interfaced to a
    large variety of external tools and software, including R and other
    libraries.
  doc_url: https://wiki.dseams.info/
  dev_url: https://github.com/d-SEAMS/seams-core
extra:
  recipe-maintainers:
    - HaoZeke
    - amritagos
